SELECT S.SALEID,S.PRBSTATUS,S.SALESTATUS,S.SALEPIORITY
FROM XININSURE.SALE S
WHERE S.SALEBOOKCODE = 'MTI'
  AND (S.SALEPIORITY IN (1, 2, 3) OR S.SALEPIORITY IS NULL)
  AND S.SALESTATUS IN ('O', 'V')
  AND S.PRBSTATUS = 'C'
  AND S.PRBCOVERDATE > NVL(:qdate, SYSDATE)
  AND S.PRBCANCELDATE >= TRUNC(NVL(:qdate, SYSDATE))
  AND S.PRBCANCELDATE <  TRUNC(NVL(:qdate, SYSDATE)) + 1
  AND NOT EXISTS (
        SELECT 1
        FROM XININSURE.SALEACTION A
        WHERE A.SALEID = S.SALEID
          AND A.ACTIONID = '5911'
          AND A.ACTIONSTATUS = 'Y'
  )
